### ISSUE TITLE
Merge Extension Libraries for OpenAPI Generator

### ISSUE THREAD

**Issue by xC0dex** [martincostello/openapi-extensions#131]
Hey @martincostello,

I’ve reviewed your awesome library and it looks like we share a common goal: Providing useful extension methods for the built-in OpenAPI generator. I’ve also developed a library called [`APIWeaver.OpenApi`](https://github.com/xC0dex/APIWeaver), which contains some extension methods.
I believe it would be great for the developers if we could combine these extensions into one unified library. This way, developers wouldn’t need to install multiple extension libraries.

What's your thoughts on this idea? Or was it not your intention for this library to be actively maintained over the long term?

I'd love to hear your opinion.

Justin

**Comment by martincostello** [comment]
To be honest, I'm not sure.

This library mainly came about from the fact I had Swashbuckle-based equivalents of these transformers (particularly the examples one) in multiple different applications in a copy-pasta manner, and I took the opportunity to combine them into a library as part of migrating them all to use the new .NET 9 OpenAPI package (plus it was a fun small side-project to do).

APIWeaver looks much more fully-featured than this library is (or intending to be) so happy for you to run with it to do whatever your vision for it is - I'm not going to be "competing" with you for breadth of features or to be the most popular extension library 😃.

I'm intending to maintain this library (because I depend on it now), but I don't think I'm looking for it to turn into a big "thing" or to take on helping maintain another multi-person project right now (Swashbuckle, Polly and some other things are plenty).

I'd be happy to help you out with getting equivalent functionality in APIWeaver though.

**Comment by xC0dex** [comment]
Thank you very much for the explanation! The original idea behind `APIWeaver` was also different, but the scope changed and I thought it made sense to provide useful extension methods, as something similar didn't exist for the built-in generator. I’m also uncertain where `APIWeaver` will be in one year, whether it will be accepted and used by the community or not.

I would highly appreciate any kind of contribution!
